# Generated by NexaBuilder — review and adjust ports/CMD for your repo.
# This file is only added when no Dockerfile exists at the repo root.

FROM nginx:alpine
COPY . /usr/share/nginx/html
RUN printf %s \
  'server { listen 3000; root /usr/share/nginx/html; location / { try_files $uri $uri/ /index.html; } }' \
  > /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
